version: 2
updates:
  # Rust dependencies
  - package-ecosystem: "cargo"
    directory: "/backend/rust-engine"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "MWANGAZA-LAB"
    assignees:
      - "MWANGAZA-LAB"

  # Node.js dependencies for orchestrator
  - package-ecosystem: "npm"
    directory: "/backend/node-orchestrator"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "MWANGAZA-LAB"
    assignees:
      - "MWANGAZA-LAB"

  # Node.js dependencies for mobile app
  - package-ecosystem: "npm"
    directory: "/mobile"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "MWANGAZA-LAB"
    assignees:
      - "MWANGAZA-LAB"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "MWANGAZA-LAB"
    assignees:
      - "MWANGAZA-LAB"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "MWANGAZA-LAB"
    assignees:
      - "MWANGAZA-LAB"
