{{- if and .Values.apiGateway.enabled .Values.apiGateway.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "satsconnect.fullname" . }}-api-gateway-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "satsconnect.labels" . | nindent 4 }}
    component: api-gateway
  annotations:
    {{- toYaml .Values.apiGateway.ingress.annotations | nindent 4 }}
spec:
  {{- if .Values.apiGateway.ingress.className }}
  ingressClassName: {{ .Values.apiGateway.ingress.className }}
  {{- end }}
  {{- if .Values.apiGateway.ingress.tls }}
  tls:
    {{- range .Values.apiGateway.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.apiGateway.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "satsconnect.fullname" $ }}-api-gateway
                port:
                  number: {{ $.Values.apiGateway.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
