{{- if .Values.secrets.create }}
{{- if .Values.rustEngine.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "satsconnect.fullname" . }}-rust-engine-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "satsconnect.labels" . | nindent 4 }}
    component: rust-engine
type: Opaque
data:
  {{- if .Values.secrets.rustEngine.bitcoinRpcUrl }}
  bitcoin-rpc-url: {{ .Values.secrets.rustEngine.bitcoinRpcUrl | b64enc }}
  {{- end }}
  {{- if .Values.secrets.rustEngine.bitcoinRpcUser }}
  bitcoin-rpc-user: {{ .Values.secrets.rustEngine.bitcoinRpcUser | b64enc }}
  {{- end }}
  {{- if .Values.secrets.rustEngine.bitcoinRpcPassword }}
  bitcoin-rpc-password: {{ .Values.secrets.rustEngine.bitcoinRpcPassword | b64enc }}
  {{- end }}
{{- end }}

{{- if .Values.apiGateway.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "satsconnect.fullname" . }}-api-gateway-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "satsconnect.labels" . | nindent 4 }}
    component: api-gateway
type: Opaque
data:
  {{- if .Values.secrets.apiGateway.jwtSecret }}
  jwt-secret: {{ .Values.secrets.apiGateway.jwtSecret | b64enc }}
  {{- end }}
  {{- if .Values.secrets.apiGateway.mpesaConsumerKey }}
  mpesa-consumer-key: {{ .Values.secrets.apiGateway.mpesaConsumerKey | b64enc }}
  {{- end }}
  {{- if .Values.secrets.apiGateway.mpesaConsumerSecret }}
  mpesa-consumer-secret: {{ .Values.secrets.apiGateway.mpesaConsumerSecret | b64enc }}
  {{- end }}
  {{- if .Values.secrets.apiGateway.mpesaShortcode }}
  mpesa-shortcode: {{ .Values.secrets.apiGateway.mpesaShortcode | b64enc }}
  {{- end }}
  {{- if .Values.secrets.apiGateway.mpesaPasskey }}
  mpesa-passkey: {{ .Values.secrets.apiGateway.mpesaPasskey | b64enc }}
  {{- end }}
  {{- if .Values.secrets.apiGateway.coinmarketcapApiKey }}
  coinmarketcap-api-key: {{ .Values.secrets.apiGateway.coinmarketcapApiKey | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
